version: '3.8'

services:
  postgres:
    image: 'postgres:18.1'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=shopping_db'
    ports:
      - '5432:5432'
    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'

  keycloak:
    image: 'keycloak/keycloak:26.6.2'
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    ports:
      - '8080:8080'
    command: start-dev
    volumes:
      - './custom-keycloak/target-public/custom-keycloak.jar:/opt/keycloak/providers/my-custom-plugin.jar'
      - './custom-keycloak/target-public/postgresql-42.7.11.jar:/opt/keycloak/providers/postgresql-42.7.11.jar'

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=shopping
      - KEYCLOAK_CLIENT_ID=shopping-client
      - KEYCLOAK_CLIENT_SECRET=change-me
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - JWT_ACCESS_SECRET=bXktYWNjZXNzLXNlY3JldC1rZXktZm9yLXNob3BwaW5nLWFwcC0yNTY=
      - JWT_REFRESH_SECRET=bXktcmVmcmVzaC1zZWNyZXQta2V5LWZvci1zaG9wcGluZy1hcHAtMjU2
      - JWT_ACCESS_EXPIRATION_MINUTES=15
      - JWT_REFRESH_EXPIRATION_DAY=7
      - ANGULAR_URL=http://localhost:4200
      - USER_SERVICE_URL=http://user-service:8081
    ports:
      - "8084:8084"
    depends_on:
      - keycloak
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/src

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/shopping_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  report-service:
    build: ./report-service
    container_name: report-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopping_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./user-service/src

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopping_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./ticket-service/src

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
      - report-service
      - ticket-service
    develop:
      watch:
        - action: rebuild
          path: ./api-gateway/src